services:
  dotnet_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: homework
    
  dotnet_main:
    image: dotnet-web
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__Default: "Host=dotnet_postgres;Username=user;Password=password;Database=homework"
    depends_on:
      - dotnet_postgres

#  dotnet_mailing:
#    image: dotnet-web
#    
#  dotnet_storage:
#    image: dotnet-web
#    
#  dotnet_rabbitmq:
#    image: rabbitmq:3-alpine
#  
#  dotnet_minio:
#    image: minio/minio:latest
#  
#  dotnet_mongodb:
#    image: mongo:latest
#  
#  dotnet_jaeger:
#    image: jaegertracing/all-in-one:latest